---
driver:
  name: vagrant
  network:
  - ["forwarded_port", {guest: 8153, host: 8153}]
  #- ["forwarded_port", {guest: 80, host: 8080}]
  - ["private_network", {ip: "192.168.33.33"}]

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[optuitive-gocd::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
